name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sanjacob/markdown-list@master
        with:
          file: EXAMPLE.md
          header: Cities
          item: Mexico City
      - run: ls
      - run: cat EXAMPLE.md
      - uses: actions/upload-artifact@v4
        with:
          name: Output
          path: EXAMPLE.md
